name: docker-compose-build-push.yaml

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/docker-compose-build-push.yaml'
      - 'docker/**'
      - 'python/**'
  workflow_dispatch:

jobs:
  docker_compose_build_push_pull:
    permissions:
      contents: read
      packages: write
    uses: petrochenkov-ak-lab/.github/.github/workflows/base-docker-compose-build-push.yaml@main
    secrets: inherit
