include '../postgresql.base.conf'

port = 5445

shared_buffers = 16MB
work_mem = 1MB
maintenance_work_mem = 8MB
effective_cache_size = 32MB

max_connections = 10
max_worker_processes = 10

max_parallel_workers_per_gather = 0
max_parallel_workers = 0
max_parallel_maintenance_workers = 0

max_logical_replication_workers = 2
max_sync_workers_per_subscription = 1

track_activities = off
track_counts = off
autovacuum = off

