include '../postgresql.base.conf'

port = 5443

wal_level = 'logical'

max_worker_processes = 24
max_logical_replication_workers = 12
max_sync_workers_per_subscription = 2

max_wal_size = 1GB
min_wal_size = 80MB
